id = "c++-snippets"
name = "C++ Snippets"
version = "0.1.0"
schema_version = 1
authors = ["woruo03 <woruo03@gmail.com>"]
description = "C++ snippets for the Zed IDE."
repository = "https://github.com/woruo03/cpp-snippets-for-zed"
snippets = ["./snippets/c++.json"]
